language: ruby
rvm:
  - 2.4.0
  - 2.3.1
  - 2.2.1

before_install: gem install bundler
script: bundle exec rake rspec_rubocop
notifications:
  slack:
    secure: P+BWOt+sKPUlIwxUMaD7o4bVG19nIsedyv9D1MCBJELKxTYkXOyJECSNw1f5SDf9z0n4lKhfp8SY0dVigvxdUBd9/wsGqRZMMI2sykDJ8E85cYsUb8corEnIgQtwwzkAzWzhCbmWrZe39ai1Sr5ET/7bdEJ7SXIKbFS350SOn9s=
